apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ include "inference-router.fullname" . }}-router'
  labels:
    app.kubernetes.io/name: inference-router
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
